# This workflow will push to the unstable packagecloud repo when the
# trigger is not a tag

name: Release

on:
  push:
    branches:
      - master
      - release-**
      - goreleaser/*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
            
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          
      - name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          push: startsWith(github.ref, 'refs/heads')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to tyk-sync-unstable
        if: startsWith(github.ref, 'refs/heads')
        uses: ./.github/actions/packagecloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        with:
          repo: 'tyk/tyk-sync-unstable'
          dir: 'dist'

      - name: Push to tyk-sync
        if: startsWith(github.ref, 'refs/tags')
        uses: ./.github/actions/packagecloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        with:
          repo: 'tyk/tyk-sync'
          dir: 'dist'
      
